/// Flutter icons ServiceIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ServiceIcons
///      fonts:
///       - asset: fonts/ServiceIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ServiceIcons {
  ServiceIcons._();

  static const _kFontFam = 'ServiceIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
