/// Flutter icons ChatIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ChatIcons
///      fonts:
///       - asset: fonts/ChatIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ChatIcons {
  ChatIcons._();

  static const _kFontFam = 'ChatIcons';
  static const String? _kFontPkg = null;

  static const IconData send = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
