/// Flutter icons DetailsIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DetailsIcons
///      fonts:
///       - asset: fonts/DetailsIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DetailsIcons {
  DetailsIcons._();

  static const _kFontFam = 'DetailsIcons';
  static const String? _kFontPkg = null;

  static const IconData delete = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
