/// Flutter icons AdminNavigationIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AdminNavigationIcons
///      fonts:
///       - asset: fonts/AdminNavigationIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AdminNavigationIcons {
  AdminNavigationIcons._();

  static const _kFontFam = 'AdminNavigationIcons';
  static const String? _kFontPkg = null;

  static const IconData orders =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calculator =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData conclusion =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
